In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1,2, None] , dtype = 'float64')

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.dtype

dtype('float64')

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7]) 

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
#second method to same thing is :
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
#these were for series methods



In [17]:
#NOW FOR DATAFRAME

In [18]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [19]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [20]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [21]:
data.dropna(how = "all") #Passing how="all" will drop only rows that are all NA:

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [22]:
# #these functions return new objects by default and do not modify
# the contents of the original object.

In [23]:
data[4] = np.nan

In [24]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [25]:
data.dropna(axis = "columns", how = "all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [26]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [27]:
df

,0,1,2
0,2.287287,0.356764,-0.077464
1,-0.471408,-0.960274,-0.473436
2,-0.932750,-0.092673,-0.347303
3,-0.573627,0.738560,-0.586138
4,2.044564,1.578502,-0.352080
5,0.531592,-0.301045,0.093911
6,1.997248,-2.513785,0.247633


In [28]:
df.iloc[:4,1] = np.nan

In [29]:
df

,0,1,2
0,2.287287,NaN,-0.077464
1,-0.471408,NaN,-0.473436
2,-0.932750,NaN,-0.347303
3,-0.573627,NaN,-0.586138
4,2.044564,1.578502,-0.352080
5,0.531592,-0.301045,0.093911
6,1.997248,-2.513785,0.247633


In [30]:
df.iloc[:6,2] = np.nan

In [31]:
df

,0,1,2
0,2.287287,NaN,NaN
1,-0.471408,NaN,NaN
2,-0.932750,NaN,NaN
3,-0.573627,NaN,NaN
4,2.044564,1.578502,NaN
5,0.531592,-0.301045,NaN
6,1.997248,-2.513785,0.247633


In [32]:
df.dropna()

,0,1,2
6,1.997248,-2.513785,0.247633


In [33]:
df.dropna(thresh = 2)

,0,1,2
4,2.044564,1.578502,NaN
5,0.531592,-0.301045,NaN
6,1.997248,-2.513785,0.247633


In [34]:
df.fillna(0)

,0,1,2
0,2.287287,0.000000,0.000000
1,-0.471408,0.000000,0.000000
2,-0.932750,0.000000,0.000000
3,-0.573627,0.000000,0.000000
4,2.044564,1.578502,0.000000
5,0.531592,-0.301045,0.000000
6,1.997248,-2.513785,0.247633


In [35]:
df.fillna({1: 0.5, 2: 0})

,0,1,2
0,2.287287,0.500000,0.000000
1,-0.471408,0.500000,0.000000
2,-0.932750,0.500000,0.000000
3,-0.573627,0.500000,0.000000
4,2.044564,1.578502,0.000000
5,0.531592,-0.301045,0.000000
6,1.997248,-2.513785,0.247633


In [36]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [37]:
df

,0,1,2
0,-0.380757,-0.562529,0.827448
1,0.777844,-0.478411,0.424030
2,0.173225,-1.420216,-1.827402
3,0.612265,-0.982981,-1.299676
4,-0.062153,0.156553,0.389273
5,0.691972,0.637667,1.374168


In [38]:
df.iloc[2:,1] = np.nan  #PYTHON KA NAN IS PANDA KA NA 

In [39]:
df

,0,1,2
0,-0.380757,-0.562529,0.827448
1,0.777844,-0.478411,0.424030
2,0.173225,NaN,-1.827402
3,0.612265,NaN,-1.299676
4,-0.062153,NaN,0.389273
5,0.691972,NaN,1.374168


In [40]:
df.iloc[3:,2] = np.nan

In [41]:
df

,0,1,2
0,-0.380757,-0.562529,0.827448
1,0.777844,-0.478411,0.424030
2,0.173225,NaN,-1.827402
3,0.612265,NaN,NaN
4,-0.062153,NaN,NaN
5,0.691972,NaN,NaN


In [42]:
# df.fillna(method="ffill")  REMOVED FROM PANDAS
df.ffill()

,0,1,2
0,-0.380757,-0.562529,0.827448
1,0.777844,-0.478411,0.424030
2,0.173225,-0.478411,-1.827402
3,0.612265,-0.478411,-1.827402
4,-0.062153,-0.478411,-1.827402
5,0.691972,-0.478411,-1.827402


In [43]:
df.ffill(limit=2)

,0,1,2
0,-0.380757,-0.562529,0.827448
1,0.777844,-0.478411,0.424030
2,0.173225,-0.478411,-1.827402
3,0.612265,-0.478411,-1.827402
4,-0.062153,NaN,-1.827402
5,0.691972,NaN,NaN


In [44]:
data = pd.Series([1., np.nan, 4., 6., np.nan])

In [45]:
data

0    1.0
1    NaN
2    4.0
3    6.0
4    NaN
dtype: float64

In [46]:
data.fillna(data.mean())

0    1.000000
1    3.666667
2    4.000000
3    6.000000
4    3.666667
dtype: float64

In [47]:
data.mean()

np.float64(3.6666666666666665)

## DATA TRANSFORMATION

#Removing Duplicates

In [48]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [49]:
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [50]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [51]:
# #duplicated() returns a Boolean Series indicating whether
# each row is a duplicate (its column values are exactly equal to those in an earlier row)
# or not

In [52]:
data.drop_duplicates()
#drop_duplicates returns a DataFrame with rows where the duplicated
# array is False filtered out

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [53]:
data["v1"] = range(7)

In [54]:
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [55]:
data.drop_duplicates(subset=["k1"])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [56]:
data.drop_duplicates(["k1", "k2"], keep="last")

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


#Transforming Data Using a function or mapping

In [57]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",                          
"pastrami", "corned beef", "bacon","pastrami","honey ham", "nova lox"], "ounces" : [4,3,12,6,7.5,8,3,5,6]})
  

In [58]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [59]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}

In [60]:
data["animal"] = data["food"].map(meat_to_animal)


In [61]:
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


In [62]:
 def get_animal(x):
   ....:     return meat_to_animal[x]

In [63]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

#Replacing Values

In [64]:
 data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [65]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [66]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [67]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [68]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

#Renaming Axis Indexes

In [69]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
....:                     
index=["Ohio", "Colorado", "New York"],
....:                     
columns=["one", "two", "three", "four"])

In [70]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [71]:
def transform(x):
    return x[:4].upper()

In [72]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [73]:
# map() = replace values using a dictionary/function|

In [74]:
data.index= data.index.map(transform)

In [75]:
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [76]:
data.rename(index=str.title, columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [77]:
 data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

,one,two,peekaboo,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [78]:
# #rename saves you from the chore of copying the DataFrame manually and assigning
# new values to its index and columns attributes

#Discretization and Binning

In [79]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [80]:
bins = [18, 25, 35,60 , 100]

In [81]:
age_categories = pd.cut(ages,bins)

In [82]:
age_categories 

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [83]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [84]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [85]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [86]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [87]:
pd.cut(ages, bins, right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [88]:
 group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [89]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [90]:
data = np.random.uniform(size = 20)

In [91]:
data


array([0.34364139, 0.37306343, 0.81264411, 0.47851806, 0.2571867 ,
       0.18887464, 0.54318625, 0.28825796, 0.13453326, 0.0389397 ,
       0.31976368, 0.70122619, 0.29172501, 0.5491169 , 0.79292517,
       0.68639748, 0.21226086, 0.52246021, 0.70556534, 0.93367173])

In [92]:
 pd.cut(data, 4, precision=2)

[(0.26, 0.49], (0.26, 0.49], (0.71, 0.93], (0.26, 0.49], (0.038, 0.26], ..., (0.49, 0.71], (0.038, 0.26], (0.49, 0.71], (0.49, 0.71], (0.71, 0.93]]
Length: 20
Categories (4, interval[float64, right]): [(0.038, 0.26] < (0.26, 0.49] < (0.49, 0.71] < (0.71, 0.93]]

In [93]:
data = np.random.standard_normal(1000)

In [94]:
data

array([-9.79964895e-01,  1.24455520e+00,  5.51231108e-01,  8.32262675e-02,
        2.67147502e-01, -1.01594724e+00, -1.58008397e-01,  8.94722061e-01,
        3.04087352e-02, -8.18448002e-01, -2.21565090e+00, -5.99863809e-01,
        3.69367342e-01, -2.67094393e-01,  7.26053157e-01, -2.38313573e+00,
       -2.19453863e+00, -2.30150564e-01,  3.17920382e-01,  4.10415493e-02,
        9.01790572e-01,  7.60610413e-01, -2.08302652e-02, -2.71645540e+00,
       -8.17793216e-01,  1.03245048e+00,  1.30922356e+00,  1.89773552e+00,
        7.36768911e-01, -2.12276524e-01, -2.69918130e+00, -1.14831574e+00,
        5.07700293e-01, -4.99912877e-01,  4.36260624e-01, -1.15302414e+00,
        7.45522731e-01, -2.29600463e-01,  2.04945318e-01, -5.39856653e-01,
       -5.06754868e-02, -9.29298664e-01, -6.31636431e-03,  1.65035929e-02,
        1.14489752e+00, -1.66582876e+00,  1.70982842e+00,  1.07818481e-02,
       -5.00756735e-01, -3.87390280e-02,  1.19987848e-01,  1.41092156e+00,
        7.58741192e-01, -

In [95]:
quartiles = pd.qcut(data, 4, precision=2)

In [96]:
quartiles

[(-3.86, -0.74], (0.6, 3.73], (-0.043, 0.6], (-0.043, 0.6], (-0.043, 0.6], ..., (-0.74, -0.043], (-3.86, -0.74], (-0.043, 0.6], (-0.043, 0.6], (0.6, 3.73]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.86, -0.74] < (-0.74, -0.043] < (-0.043, 0.6] < (0.6, 3.73]]

In [97]:
# pd.count(quartiles) REDO IT KYUNKI YEH PANDAS SE REMOVE KR DIYA GYA HAI !!

In [98]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.856, -1.346]     100
(-1.346, -0.0434]    400
(-0.0434, 1.178]     400
(1.178, 3.725]       100
Name: count, dtype: int64

# Detecting and Filtering Outliers 

In [99]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [100]:
data

,0,1,2,3
0,-0.212897,-0.060719,-1.614923,1.380346
1,0.525301,-0.176962,-0.140458,-1.055940
2,-0.830090,0.262803,0.127515,1.003966
3,0.999323,-0.838531,-0.048311,-1.628016
4,-0.205463,-2.080079,0.932869,-0.465225
...,...,...,...,...
995,-1.532725,-0.590047,-0.208768,0.914519
996,0.216267,0.680848,0.394335,-0.454466
997,0.437142,1.031806,1.180285,0.541025
998,0.574865,-1.762439,0.372532,-0.187953


In [101]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.010296,0.054778,-0.026323,-0.011895
std,1.014813,1.047135,0.975607,1.026570
min,-3.108883,-3.553997,-3.593102,-3.149369
25%,-0.700471,-0.621732,-0.702934,-0.682407
50%,-0.002069,0.042256,0.032143,0.022751
75%,0.731051,0.734517,0.635348,0.691077
max,3.386747,3.827184,2.565046,4.023178


In [102]:
col = data[2]

In [103]:
 col[col.abs() > 3]

344   -3.593102
Name: 2, dtype: float64

In [104]:
data[(data.abs() > 3).any(axis="columns")]

,0,1,2,3
6,0.119480,-2.964096,0.884796,3.317599
185,0.197865,-0.262157,0.406094,4.023178
238,2.246237,-3.253652,-0.877089,-0.079226
344,-2.734788,0.427542,-3.593102,0.596495
359,3.386747,-0.471304,0.617561,-1.699915
502,-1.118505,3.827184,-1.122458,-0.603058
513,-0.169793,0.373005,-1.148074,-3.072748
540,-0.606967,-3.332711,-0.542203,-0.127698
610,0.733231,-3.553997,-0.169867,-0.478223
622,0.484912,-3.231536,-0.949528,0.268066


In [105]:
data[data.abs() > 3] = np.sign(data) * 3

data.describe()

In [106]:
 # np.sign(data) produces 1 and –1

In [107]:
np.sign(data).head()

,0,1,2,3
0,-1.0,-1.0,-1.0,1.0
1,1.0,-1.0,-1.0,-1.0
2,-1.0,1.0,1.0,1.0
3,1.0,-1.0,-1.0,-1.0
4,-1.0,-1.0,1.0,-1.0


# Permutation and Random Sampling 

In [108]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [109]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [110]:
sampler = np.random.permutation(5)

In [111]:
sampler

array([2, 4, 3, 0, 1], dtype=int32)

In [112]:
df.take(sampler)

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13


In [113]:
df.iloc[sampler]

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13


In [114]:
column_sampler = np.random.permutation(7)

In [115]:
column_sampler

array([4, 6, 2, 1, 3, 0, 5], dtype=int32)

In [116]:
df.take(column_sampler, axis="columns")

,4,6,2,1,3,0,5
0,4,6,2,1,3,0,5
1,11,13,9,8,10,7,12
2,18,20,16,15,17,14,19
3,25,27,23,22,24,21,26
4,32,34,30,29,31,28,33


In [117]:
df.sample(n = 3)

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
2,14,15,16,17,18,19,20
0,0,1,2,3,4,5,6


In [118]:
df.sample(n=3, replace = True)

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20


In [119]:
choices = pd.Series([5, 7, -1, 6, 4])

In [120]:
choices.sample(n=10, replace=True)

4    4
3    6
1    7
3    6
0    5
2   -1
2   -1
1    7
0    5
0    5
dtype: int64

In [121]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [122]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [123]:
pd.get_dummies(df)

,data1,key_a,key_b,key_c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False


In [124]:
pd.get_dummies(df["key"])

,a,b,c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [125]:
#here false = .0 and true = 1

In [126]:
dummies = pd.get_dummies(df["key"], prefix = "key")

In [127]:
df_with_dummy = df[["data1"]].join(dummies)

In [128]:
df_with_dummy

,data1,key_a,key_b,key_c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False


In [129]:
 mnames = ["movie_id", "title", "genres"]

In [130]:
movies = pd.DataFrame( {"movie_id" : list(range(1 ,11)), "title" : ["Toy Story (1995)","Jumanji (1995)","Grumpier Old Man(1995)", "Waiting to Exhale (1995) ", " Father of the Bride Part II (1995)","Heat(1995)"," Sabrina(1995) ","Tom and Huck (1995)  ","Sudden Death (1995)","GoldenEye (1995)"], 
                       "genres" : ["Animation|Children's|Comedy","Adventure|Children's|Fantasy","Comedy|Romance","Comedy|Drama"," Comedy","Action|Crime|Thriller","  Comedy|Romance" ,"Adventure|Children's"," Action","Action|Adventure|Thriller"]})
                       

In [131]:
movies

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Man(1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat(1995),Action|Crime|Thriller
6,7,Sabrina(1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [132]:
movies[:10]

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Man(1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat(1995),Action|Crime|Thriller
6,7,Sabrina(1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [133]:
dummies = movies["genres"].str.get_dummies("|")

In [134]:
dummies.iloc[:10, :6]

,Comedy,Action,Comedy,Action,Adventure,Animation
0,0,0,0,0,0,1
1,0,0,0,0,1,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,1,0,0,0
5,0,0,0,1,0,0
6,1,0,0,0,0,0
7,0,0,0,0,1,0
8,0,1,0,0,0,0
9,0,0,0,1,1,0


In [135]:
 movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [136]:
movies_windic.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
Genre_  Comedy                                0
Genre_ Action                                 0
Genre_ Comedy                                 0
Genre_Action                                  0
Genre_Adventure                               0
Genre_Animation                               1
Genre_Children's                              1
Genre_Comedy                                  1
Genre_Crime                                   0
Genre_Drama                                   0
Genre_Fantasy                                 0
Genre_Romance                                 0
Genre_Thriller                                0
Name: 0, dtype: object

In [137]:
movies_windic.iloc[1]

movie_id                                       2
title                             Jumanji (1995)
genres              Adventure|Children's|Fantasy
Genre_  Comedy                                 0
Genre_ Action                                  0
Genre_ Comedy                                  0
Genre_Action                                   0
Genre_Adventure                                1
Genre_Animation                                0
Genre_Children's                               1
Genre_Comedy                                   0
Genre_Crime                                    0
Genre_Drama                                    0
Genre_Fantasy                                  1
Genre_Romance                                  0
Genre_Thriller                                 0
Name: 1, dtype: object

In [138]:
np.random.seed(12345)

In [139]:
values = np.random.uniform(size = 10)

In [140]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [141]:
bins =  [0, 0.2, 0.4, 0.6, 0.8, 1]

In [142]:
 pd.get_dummies(pd.cut(values, bins))

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,False,False,False,False,True
1,False,True,False,False,False
2,True,False,False,False,False
3,False,True,False,False,False
4,False,False,True,False,False
5,False,False,True,False,False
6,False,False,False,False,True
7,False,False,False,True,False
8,False,False,False,True,False
9,False,False,False,True,False


In [143]:
s = pd.Series([1,2,3,None])

In [144]:
s.dtype

dtype('float64')

In [145]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [146]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [147]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [148]:
s.dtype

Int64Dtype()

In [149]:
s[3]

<NA>

In [150]:
s[3] is pd.NA

True

In [151]:
s = pd.Series([1,2,3,None], dtype = "Int64")

In [152]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [153]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [154]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [155]:
s.dtype

<StringDtype(na_value=<NA>)>

In [156]:
s.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [157]:
df = pd.DataFrame({"A": [1, 2, None, 4],
"B": ["one", "two", "three", None],"C": [False, None, False, True]})

In [158]:
df

,A,B,C
0,1.0,one,False
1,2.0,two,None
2,NaN,three,False
3,4.0,NaN,True


In [159]:
df["A"] = df["A"].astype("Int64")

In [160]:
df["B"] = df["B"].astype("string")

In [161]:
df["C"] = df["C"].astype("boolean")

In [162]:
df

,A,B,C
0,1,one,False
1,2,two,<NA>
2,<NA>,three,False
3,4,<NA>,True


## String Manipulation

**Python Built-In String Object Methods

In [163]:
val = "a,b, guido"

In [164]:
val.split(",")

['a', 'b', ' guido']

In [165]:
pieces = [x.strip() for x in val.split(",")]

In [166]:
pieces

['a', 'b', 'guido']

In [167]:
first , second , third = pieces

In [168]:
first + "::" + second + "::" + third

'a::b::guido'

In [169]:
# "::" = two colon delimiter

In [170]:
"::".join(pieces)  #second method to the same shi

'a::b::guido'

In [171]:
"guido" in val 

True

In [172]:
val.index(",")

1

In [173]:
val.find(":")

-1

In [174]:
# find returns -1 but index returns error if the string is not founnd inthe dataframe 

In [175]:
val.count(",")

2

In [176]:
val.replace(",","<<")

'a<<b<< guido'

In [177]:
val.replace(",","")

'ab guido'

**Regular expression


In [178]:
import re


In [179]:
text = "foo   bar\t baz  \tqux"

In [180]:
re.split(r"\s+", text )

['foo', 'bar', 'baz', 'qux']

In [181]:
regex = re.compile(r"\s+")

In [182]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [183]:
regex.findall(text)

['   ', '\t ', '  \t']

In [184]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [185]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [186]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [187]:
m = regex.search(text)

In [188]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [189]:
text[m.start():m.end()]

'dave@google.com'

In [190]:
print(regex.match(text))

None


In [191]:
print(regex.sub("REDATED", text))

Dave REDATED
Steve REDATED
Rob REDATED
Ryan REDATED


In [192]:
 pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [193]:
regex =  re.compile(pattern, flags=re.IGNORECASE)

In [194]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [195]:
regex

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
           re.IGNORECASE|re.UNICODE)

In [196]:
m = regex.match("wesm@bright.net")

In [197]:
m.groups()

('wesm', 'bright', 'net')

In [198]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [199]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


**STRING FUNCTION IN PANDAS

In [200]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
.....:         
"Rob": "rob@gmail.com", "Wes": np.nan}

In [201]:
data = pd.Series(data)

In [202]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [203]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [204]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [205]:
data_as_strings_ext = data.astype('string')

In [206]:
data_as_strings_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [207]:
data_as_strings_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [208]:
pattern =  r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [209]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [210]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [211]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [212]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [213]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: str

In [214]:
data.str.extract(pattern , flags = re.IGNORECASE)

,0,1,2
Dave,dave,google,com
Steve,steve,gmail,com
Rob,rob,gmail,com
Wes,NaN,NaN,NaN


In [215]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [216]:
data.str.endswith('pat')

Dave     False
Steve    False
Rob      False
Wes      False
dtype: bool

In [217]:
data.str.count("gmail")

Dave     0.0
Steve    1.0
Rob      1.0
Wes      NaN
dtype: float64

## Categorical Data

In [218]:
values = pd.Series(['apple','orange','dingo','apple']*2)

In [219]:
values

0     apple
1    orange
2     dingo
3     apple
4     apple
5    orange
6     dingo
7     apple
dtype: str

In [220]:
values.unique()

<ArrowStringArray>
['apple', 'orange', 'dingo']
Length: 3, dtype: str

In [221]:
pd.unique(values)

<ArrowStringArray>
['apple', 'orange', 'dingo']
Length: 3, dtype: str

In [222]:
pd.Series(values).value_counts() #new version of value_counts for pandas

apple     4
orange    2
dingo     2
Name: count, dtype: int64

In [223]:
values.value_counts()

apple     4
orange    2
dingo     2
Name: count, dtype: int64

In [224]:
 values = pd.Series([0, 1, 0, 0] * 2)

In [225]:
values


0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [226]:
dim = pd.Series(['apple', 'orange'])

In [227]:
dim

0     apple
1    orange
dtype: str

In [228]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: str

In [229]:
 fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [230]:
N = len(fruits)

In [231]:
rng = np.random.default_rng(seed = 12345)

In [232]:
df = pd.DataFrame({'fruit':fruits, 'basket_id': np.arange(N), 'count': rng.integers(3,15,size=N), 'weight' : rng.uniform(0,4,size = N)},
                  columns = ['basket_id','fruit','count','weight'])


In [233]:
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [234]:
# conversion of fruit array to categorical 
fruit_cat = df['fruit'].astype('category')

In [235]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [236]:
fruit_cat.dtype

CategoricalDtype(categories=['apple', 'orange'], ordered=False, categories_dtype=str)

In [237]:
c = fruit_cat.array

In [238]:
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, str): ['apple', 'orange']

In [239]:
type(c)

pandas.Categorical

In [240]:
c.categories

Index(['apple', 'orange'], dtype='str')

In [241]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [242]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [243]:
df['fruit'] = df['fruit'].astype('category')

In [244]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [245]:
# pandas.Categorical from other types of python sequences
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [246]:
my_categories 

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, str): ['bar', 'baz', 'foo']

In [247]:
my_categories.dtype

CategoricalDtype(categories=['bar', 'baz', 'foo'], ordered=False, categories_dtype=str)

In [248]:
categories = ['foo', 'bar', 'baz']

In [249]:
codes = [0, 1, -1, 0, 0, 1]

In [250]:
categories 

['foo', 'bar', 'baz']

In [251]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [252]:
my_cats_2

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo', 'bar', 'baz']

In [253]:
dingo = ['chamar', 'bnsdk', 'lwdyum']

In [254]:
l = pd.Categorical.from_codes( codes,dingo)

In [255]:
l

['chamar', 'bnsdk', NaN, 'chamar', 'chamar', 'bnsdk']
Categories (3, str): ['chamar', 'bnsdk', 'lwdyum']

In [256]:
ordered_cat = pd.Categorical.from_codes(codes,categories, ordered = True)

In [257]:
ordered_cat

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [258]:
#another method to make unordered categorical to ordered categorical is :
my_cats_2.as_ordered()

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [259]:
rng = np.random.default_rng(seed = 12345)

In [260]:
draws = rng.standard_normal(1000)

In [261]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [262]:
bins = pd.qcut(draws,4)

In [263]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [264]:
bins = pd.qcut(draws, 4 , labels = ['Q1','Q2','Q3','Q4'])

In [265]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [266]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [267]:
bins = pd.Series(bins, name = 'quartile')

In [268]:
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [269]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [270]:
results

,quartile,count,min,max
0,Q1,250,-3.119609,-0.678494
1,Q2,250,-0.673305,0.008009
2,Q3,250,0.018753,0.686183
3,Q4,250,0.688282,3.211418


In [271]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [272]:
#this quartile contains the original categorical information 

In [273]:
#better perfromance with categoricals

In [274]:
N = 10_000_000

In [275]:
labels = pd.Series(['foo','bar','baz','qux']*(N//4))  #(N//4) means divide and keep the absolute value that is the integer value not the floating value 

In [276]:
categories = labels.astype('category')

In [277]:
labels.memory_usage(deep = True)

110000132

In [278]:
categories.memory_usage(deep = True)

10000177

In [279]:
%time _ = labels.astype('category')

CPU times: total: 297 ms
Wall time: 274 ms


In [280]:
%timeit labels.value_counts()

169 ms ± 3.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [281]:
%timeit categories.value_counts()

37.3 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [282]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [283]:
cat_s = s.astype('category')

In [284]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [285]:
cat_s.cat.codes  #Show the internal integer codes for each category

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [286]:
 cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='str')

In [287]:
#if the set of categories for this data extends beyond 4 then we use the following method 

In [288]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [289]:
actual_categories

['a', 'b', 'c', 'd', 'e']

In [290]:
cat_s2 = cat_s.cat.set_categories(actual_categories) #Replace / redefine the full list of allowed categories

In [291]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [292]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [293]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [294]:
 cat_s3 = cat_s[cat_s.isin(['a', 'b'])] #Keep only rows where value is "a" or "b"

In [295]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [296]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']

In [297]:
#this removed c and d here

In [298]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [300]:
pd.get_dummies(cat_s, dtype = 'boolean')

,a,b,c,d
0,True,False,False,False
1,False,True,False,False
2,False,False,True,False
3,False,False,False,True
4,True,False,False,False
5,False,True,False,False
6,False,False,True,False
7,False,False,False,True


In [ ]:
#this chapter hereby ends .....................
